const envVars = {
  APP_PORT: process.env.APP_PORT,
  APP_ENVIRONMENT: process.env.APP_ENVIRONMENT,
  IMAGENIUS_APP_MONGODB_DATABASE: process.env.IMAGENIUS_APP_MONGODB_DATABASE,
  IMAGENIUS_APP_MONGODB_HOST: process.env.IMAGENIUS_APP_MONGODB_HOST,
  IMAGENIUS_APP_JWT_SECRET: process.env.IMAGENIUS_APP_JWT_SECRET,
  IMAGENIUS_APP_SESSION_SECRET: process.env.IMAGENIUS_APP_SESSION_SECRET,
  SENDGRID_AUTH_KEY: process.env.SENDGRID_AUTH_KEY,
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
  TWILIO_SERVICE_ID: process.env.TWILIO_SERVICE_ID,
  TWILIO_PHONE_NUMBER: process.env.TWILIO_PHONE_NUMBER,
  IPSTACK_API_KEY: process.env.IPSTACK_API_KEY,
};

module.exports = envVars;
